config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "users#top"
  get "search" => "search#search"
  get "home/about" => "users#about"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :users, only: [:index, :edit, :update, :show, :new] do
	member do
		get :followings, :followers
	end

end

resources :relationships, only: [:create, :destroy]
resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do
 resource :favorites, only: [:create, :destroy]
 resources :book_comments, only: [:create, :destroy]
end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

	has_many :books, dependent: :destroy
	has_many :favorites, dependent: :destroy
	has_many :book_comments, dependent: :destroy
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user
	attachment :profile_image

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end



validates :name, presence: true, length: {minimum: 2, maximum: 20}
validates :introduction,
  length: { maximum: 50 }

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :correct_user, only: [:edit, :update]

  def top
    @book = Book.new
  end

  def about
    render :about
  end


  def index
  	@user = current_user
    @book = Book.new
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def edit
  @user = User.find(params[:id])

  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path, notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  def followings
      @user  = User.find(params[:id])
      @users = @user.followings
      render 'follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'follower'
  end


  private
  def user_params
    params.require(:user).permit( :name, :profile_image, :introduction)
  end


  def correct_user
    user = User.find(params[:id])
    if current_user != user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/users/_user.html.erb
<div class="col-xs-3">
  <div class="profile-container">
    <h2>User info</h2>
    <%= attachment_image_tag user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img pull-left profile-img", fallback: "no_image.jpg" %>
    <table class = "table">
    <tr>
  		<th>name</th>
  		<th><h3 class="profile-name"><%= user.name %></h3></th>
    </tr>
    <tr>
  	 <th>introduction</th>
  	 <th><p class = "profile-introduction"><%= user.introduction %></p></th>
    </tr>

      <% @user ||= current_user %>
    <tr>
      <th>
        <p>follows</p>
      </th>
     <th>
        <a href="<%= followings_user_path(@user) %>">
        <strong id="followings" class="stat">
        <%= @user.followings.count %>
        </strong>
        </a>
     </th>
    </tr>
    <tr>
      <th>
        <p>followers</p>
      </th>
     <th>
        <a href="<%= followers_user_path(@user) %>">
        <strong id="followers" class="stat">
        <%= @user.followers.count %>
        </strong>
        </a>
      </th>
    </tr>
    </table>
  </div>
  <% if  @user.id == current_user.id %>
  <p><%= link_to "", edit_user_path(user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %></p>
<% end %>
<div class = "follow">
  <%= render 'relationships/follow', user: @user %>
</div>
  <div class = "new book">
	<h2>New book</h2>
  <%= form_for(book, url: books_path) do |f| %>
    <div class = "field">
      <div class="field_with_errors">
        <label>Title</label>
      </div>
      <div class="field_with_errors">
        <%= f.text_field :title %><br>
      </div>
    </div>
    <div class = "field">
      <div class="field_with_errors">
        <label>Opinion</label>
      </div>
      <div class="field_with_errors">
        <%= f.text_area :body %>
      </div>
    </div>
    <br><%= f.submit 'Create Book', class: "btn btn-primary col-xs-12" %></br>
    <% end %>
  </div>
</div>

app/views/users/about.html.erb
<div class = "body" >
	<div class="container" >
		<h1 >Welcome to <span class="glyphicon glyphicon-book"></span><strong >Bookers</strong>!</h1>
	</div>
</div>

app/views/users/edit.html.erb
<div class = "body">
  <div class= "container">
    <div class = "row">
      <%= form_for(@user, url: user_path(@user.id)) do |f| %>
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this product from being saved:</h2>
          <ul>
              <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <h2>User info</h2>
      <div class="col-xs-3">
        <div class="field">
          <label>Name</label>
          <%= f.text_field :name, autofocus: true, class:"form-control", id:"inputEmail", placeholder:"名前"%>
        </div> <!--名前変更-->
        <div class="field">
          <label>Image</label>
          <label class="control-label sr-only" for="inputEmail">Image</label>
          <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
        </div> <!--プロフィール画像変更-->
        <div class="field">
          <label>Introduction</label>
          <%= f.text_area :introduction, autofocus: true, class:"form-control", id:"inputEmail" %>
        </div> <!--自己紹介変更-->
        <div class = "actions">
          <%= f.submit "Update User", class: "data-disable-with" %>
        </div>
      <% end %>
      </div>
    </div>
  </div>
</body>

app/views/users/follow.html.erb
<h1>Follow User</h1>

<% if  @user.followings.count == 0 %>
<p>ユーザーはいません。</p>
<% else %>
<table class= "table table-hover table-inverse">
	<thead>
		<tr>
		<td>image</td>
		<td>name</td>
		</tr>
	</thead>
		<% @user.followings.each do |user| %>
	<tbody>
		<tr>
		<td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img pull-left profile-img", fallback: "no_image.jpg" %></td>
  		<td>  <%= user.name %> </td>
			<% user ||= current_user %>
      	<td>
        	<a href="<%= followings_user_path(user) %>">
 			フォロー数:
        	<strong id="followings" class="stat">
        	<%= user.followings.count %>
        	</strong>
        	</a>
     	</td>
    
      	<td>
        	<a href="<%= followers_user_path(user) %>">
			フォロワー数:
        	<strong id="followers" class="stat">
        	<%= user.followers.count %>
        	</strong>
        	</a>
      	</td>
  		<td><%= link_to 'Show', user_path(user) %></td>
		</tr>
	</tbody>
<% end %>
</table>
<% end %>

app/views/users/follower.html.erb
<h1>Follow User</h1>
 
 <% if  @user.followings.count == 0 %>
<p>ユーザーはいません。</p>
<% else %>
<table class= "table table-hover table-inverse">
	<thead>
		<tr>
		<td>image</td>
		<td>name</td>
		</tr>
	</thead>
		<% @user.followers.each do |user| %>
	<tbody>
		<tr>
		<td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img pull-left profile-img", fallback: "no_image.jpg" %></td>
  		<td>  <%= user.name %> </td>
  		 <% @user ||= current_user %>
    
      	<td>
        	<a href="<%= followings_user_path(user) %>">
 			フォロー数:
        	<strong id="followings" class="stat">
        	<%= user.followings.count %>
        	</strong>
        	</a>
     	</td>
    
      	<td>
        	<a href="<%= followers_user_path(user) %>">
			フォロワー数:
        	<strong id="followers" class="stat">
        	<%= user.followers.count %>
        	</strong>
        	</a>
      	</td>
  		<td><%= link_to 'Show', user_path(user) %></td>
		</tr>
	</tbody>
</table>
<% end %>
<% end %>

app/views/users/index.html.erb
<div class = "container">
  <div class="row">
    <%=render 'users/user', user: @user, book: @book %>
    <div class="col-xs-9">
      <body>
      <div class = "table-visual">
        <h2>Users</h2>
        <table class= "table table-hover table-inverse">
	       <thead>
          <tr>
	   		    <th>image</th>
	   		    <th>name</th>
			       <th colspan="3"></th>
		      </tr>
	       </thead>
         <tbody>
            <% @users.each do |users|%>
	         <tr>
              <td><%= attachment_image_tag users, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img pull-left profile-img", fallback: "no_image.jpg" %></td>
              <td><%= users.name %></td>

              <% users ||= current_user %>
              <td>
                <a>
                フォロー数:
                <strong id="followings" class="stat">
                <%= users.followings.count %>
                </strong>
                </a>
              </td>

              <td>
                <a>
                フォロワー数:
                <strong id="followers" class="stat">
                <%= users.followers.count %>
                </strong>
                </a>
              </td>

              <td><%= render 'relationships/users_follow', user: users %></td>
              <td><%= link_to "Show", user_path(users.id) %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </dody>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
	<%=render 'users/user', user: @user, book: @book %>
		<div class="col-xs-9">
		<h2>Books</h2>
		<table class= "table table-hover table-inverse"　>
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>
		<tbody>
			<% @books.each do |book|%>
				<tr>
	      			<td><%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img pull-left profile-img", fallback: "no_image.jpg" %></td>
         			<td><%=link_to book_path(book.id) do%><%= book.title %><% end %></td>
         			<td><%= book.body %></td>
         			<td>
              		<a href="#comments">コメント数:<%= book.book_comments.count %></a>
            		</td>
      		<% end %>
      			</tr>
		</tbody>
		</table>
		</div>
	</div>
</div>

app/views/users/top.html.erb
<div class="container">
	<div class="row">
  		<div class="top-message col-md-offset-3 col-md-6">
			<h1>welcome to <span class="glyphicon glyphicon-book"><strong>Bookers</strong>  !!</span></h1>
					<p>In  <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>, </p>
					<p>you can share and exchange  your opinions , inpressions , and emotions</p>
					<p> about various books!</p>

			<div class="btn-wrapper">
      			<div class="row">
					<p><%= link_to "Log in", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1" %><p>
				</div>
				<div class="row">
					<p><%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %><p>
				</div>
     		</div>
     	</div>
    </div>
</div>