config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "users#top"
  get "search" => "search#search"
  get "home/about" => "users#about"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :users, only: [:index, :edit, :update, :show, :new] do
	member do
		get :followings, :followers
	end

end

resources :relationships, only: [:create, :destroy]
resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do
 resource :favorites, only: [:create, :destroy]
 resources :book_comments, only: [:create, :destroy]
end
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :book_comments, dependent: :destroy
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

	validates :title, presence: true
  	validates :body, presence: true, length: {maximum: 200}
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
before_action :correct_user, only: [:edit, :update]

  def edit
    @book = Book.find(params[:id])

  end

def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "Book was successfully updated."
    else
      render :edit
    end
end

  def create
    @book = Book.new(book_params)
    @book.user_id =current_user.id
  	@user =current_user
    @books =Book.all
  	if @book.save
      flash[:notice] = "You have creatad book successfully."
      redirect_to book_path(@book)
    else
      render :index
    end
  end

  def index
    @book = Book.new
    @user = current_user
  	@books = Book.all
  end

  def show
    @booker =Book.new
  	@book = Book.find(params[:id])
    @user = @book.user
    @books = Book.all
    @book_comment = BookComment.new
  end

def destroy
  book = Book.find(params[:id])
  book.destroy
  redirect_to books_path(book), notice: "Book was successfully destroyed."
end

  private

  def book_params
    params.require(:book).permit(:title, :body )
  end


  def correct_user
    book = Book.find(params[:id])
    if current_user != book.user
      redirect_to books_path
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<div class = "container">
  <div class = "row">
    <div class = "col-md-6 col-md-offset-3">
      <h1>Editing Book</h1>
        <%= form_for(@book) do |f| %>
          <% if @book.errors.any? %>
            <div id="error_explanation">
            <h3><%= pluralize(@book.errors.count, "error") %> prohibited this product from being saved:</h3>
              <ul>
                <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              </ul>
              <% end %>
            </div>
          <% end %>
            <div class = "field">
            <label>Title</label>
              <div class="field row">
                <%= f.text_field :title,class: "col-xs-12" %><br>
              </div>
            </div>
            <div class = "field">
              <label>Opinion</label>
            </div>
            <div class= "field row">
              <%= f.text_area :body, class: "col-xs-12" %>
            </div>
            <div class = "actions row">
              <%= f.submit 'Update Book', class: "btn btn-primary col-xs-12" %>
            </div>
            <% end %>
              <%= link_to "Show", book_path(@book) %>
              |
	          <%= link_to "Back", books_path %>
    </div>
    <div class = "col-md-3"></div>
  </div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@book.errors.count, "error") %> prohibited this product from being saved:</h2>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
<% end %>
<div class="container">
  <div class="row">
  <%=render 'users/user', user: @user, book: @book %>
    <div class="col-xs-9">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td><%=link_to user_path(book.user) do%><%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img pull-left profile-img", fallback: "no_image.jpg" %><% end %></td>
            <td><%=link_to book_path(book.id) do%><%= book.title %><% end %></td>
            <td><%= book.body %></td>

            <% if book.favorited_by?(current_user) %>
            <td>
              <%= link_to book_favorites_path(book), method: :delete do %>
              <i class = "fa fa-heart" aria-hidden="true" style　=　"color: red;"></i>
              <%= book.favorites.count %>
              <% end %>
            </td>
            <% else %>
            <td>
              <%= link_to book_favorites_path(book), method: :post do %>
              <i class = "fa fa-heart-o" aria-hidden="ture" ></i>
              <%= book.favorites.count %>
              <% end %>
            </td>
            <% end %>
            <td>
              <a href="#comments">コメント数:<%= book.book_comments.count %></a>
            </td>
          <% end %>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
		<%=render 'users/user', user: @user, book: @booker %>
	<div class="col-xs-9">
			<h2>Book detail</h2>
			<table class="table">
				<thead>
					<th></th>
				</thead>
				<tbody>
	      			<tr>
	      				<td>
	      					<%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img pull-left profile-img", fallback: "no_image.jpg" %><br>
	      					<%=link_to user_path(@user.id) do%><%= @user.name %><% end %>
	      				</td>
        				<td><%=link_to book_path(@book) do%><%= @book.title %><% end %></td>
        				<td><%= @book.body %></td>
        				
        				<% if @book.favorited_by?(current_user) %>
            			<td>
              			<%= link_to book_favorites_path(@book), method: :delete do %>
              			<i class = "fa fa-heart" aria-hidden="true" style　=　"color: red;"></i>
              			<%= @book.favorites.count %>
              			<% end %>
            			</td>
            			<% else %>
            			<td>
              			<%= link_to book_favorites_path(@book), method: :post do %>
              			<i class = "fa fa-heart-o" aria-hidden="ture" ></i>
              			<%= @book.favorites.count %>
              			<% end %>
            			</td>
            			<% end %>
                  <td>
                      <a href="#comments">コメント数:<%= @book.book_comments.count %></a>
                  </td>
        				<% if  @user.id == current_user.id %>
						<td><%= link_to "Edit", edit_book_path(@book), class: "btn-sm btn-success" %></td>
        				<td><%= link_to "Destroy", book_path(@book), method: :delete, "data-confirm" => "本当に消しますか？", class: "btn-sm btn-danger" %></td>
        			<% end %>
        			</tr>
				</tbody>
			</table>
      <table class="table">
        <tbody>
          <tr>
          <% @book.book_comments.each do |book_comment| %>
          <td>
          <%= link_to user_path(book_comment.user) do%><%= attachment_image_tag book_comment.user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img pull-left profile-img", fallback: "no_image.jpg" %><% end %>
          <%= book_comment.user.name %>
          </td>
          <td>
            <%= book_comment.comment %>
          </td>
          <% if book_comment.user == current_user %>
            <td>
              <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn btn-danger pull-right" %>
            </td>
          <% end %>
          </tr>
          <% end %>
          
        </tbody>
      </table>
      <%= form_for [@book, @book_comment] do |f| %>
            <div class = "field">
              <label>Comment</label>
            </div>
            <div class= "field row">
              <%= f.text_area :comment, class: "col-xs-12" %>
            </div>
            <div class = "actions row">
              <%= f.submit "送信", class: "btn btn-primary col-xs-12" %>
            </div>
            <% end %>
            
		</div>
	</div>
</div>